### PR TITLE
Update Vietnamese translation

### PR DESCRIPTION
**Pull request by skyventuree**
I only see 1 line to translate... am I missing something?

(I swear I did it right this time... again.)

### CODE REVIEW

**Comment by jmmelko** [comment]
325, 328, 338

**Comment by skyventuree** [comment]
I think you actually added some line breaks into those specific lines, I see those files are up-to-date and there is no more English string to translate.
Again, if I was mistaken, please notify me, thank you.

**Comment by jmmelko** [comment]
The second other sentence to translate is:

Do yo want to continue anyway?

**Comment by skyventuree** [comment]
Oh i just received an email, sorry for not replying.
If you feel something is wrong with the translation itself, feel free to fix it.
I also will be on hiatus for now. (school works)

**Pull request merged**
