### PR TITLE
development

### PR DESCRIPTION
**Pull request by heronwr**
- Added a simple command line flag parser
- Revised configurations in command_line_player.py to use passed flags
- Updated .dockerignore and .gitignore

Update:
- ~~Added python linting action in github workflows~~
- Rollback python linting github workflow, requires further discussion

Todo : 
- [x] write documentations on flags(running -h displays a rudimentary help message on command usage)
- [x] revise advance configurations in README.md

### CODE REVIEW

**Comment by heronwr** [comment]
Please dont mind the long list of one line changes, I forgot to make a dedicated branch to test github workflows

**Review by jmmelko — CHANGES_REQUESTED** [review]
mmmmhhhh.... I think it is indeed better to have people add command-line argument instead of modifying the script. There is less chances of breaking the script, and anyway they might have forgotten to revert some changes and wonderEd why it didn’t work the way they thought it would.

Thank you, it is certainly something I will use in the future.

Before approving:
I have a question about the default value of sky_json_url. There is no fallback value for it (SKYJSON_URL = cfg["skyjson"])
So by default it is None if there is no command-line parameter passed to the script? It should be False instead. Same question for BATCH_MODE

The preference argument should be called preferences or preferences_path or pref_path or prefs_path. Unless you tell me that 'preference' is the standard way of calling it.

We should rename SONG_DIR_IN to SONG_IN_DIR or conversely change in_dir to dir_in, for consistency. (I can do this later).

config.py should be renamed Config.py, to make it clear is is not a module defining classes (as I did with Lang.py).

Btw, have you tested it?
I suppose your argument parser is something you had developed before and tested thoroughly?

**Comment by heronwr** [comment]
I adjusted the parameters for consistency, and rollback github workflows for now.

**Review by jmmelko — APPROVED** [review]
You did an incredible work, and even changed the doc.
I can only approve.

**Pull request merged**
