### PR TITLE
Fix for #70

### PR DESCRIPTION
**Pull request by jmmelko**
Ti note support in doremi + better explanation of notations

### CODE REVIEW

**Comment by t1-tracey** [comment]
I enabled changes to the test_songs so that you don't have to go to the GitHub website any more. (I added `songs_out` and `songs` directory to `.gitignore` instead.)

also in English, we use `do re mi fa so la ti do` so I added another synonym for `sol` too

**Comment by jmmelko** [comment]
What do you mean I don’t have to go to the website?
I don’t even know what .gitignore does. Does that mean I can do changes without commenting?

**Comment by t1-tracey** [comment]
Ohh never mind, I just had noticed when you made the tests e.g. doremido.txt, did you have to do it from the GitHub website? it wouldn’t register when you tried to commit from computer, this was because I added .txt files to the .gitignore

.gitignore lets you list files or file extensions to ignore when doing git commits etc.

Sent from my iPad

On 21 Dec 2019, at 7:31 pm, jmmelko <notifications@github.com> wrote:

﻿

What do you mean I don’t have to go to the website?
I don’t even know what .gitignore does. Does that mean I can do changes without commenting?

**Comment by jmmelko** [comment]
I am always using the website. Maybe some day I will use the desktop app.
I never use git from the command line.
Too dangerous for my greasy paws.

**Comment by t1-tracey** [comment]
Ohhh I didn’t know that, I use github desktop

Haha aw, sometimes I used the command line for merge conflicts, with instructions from the website

Sent from my iPad

**Pull request merged**
