### PR TITLE
Translation and CSS PR

### PR DESCRIPTION
**Pull request by skyventuree**
Two following changes are made in this fork:

- Update Vietnamese Translation
- Dark mode Integration for HTML sheet. Might not work or causing elements buggy on some devices.

### CODE REVIEW

**Comment by jmmelko** [comment]
Thank you.
If it’s buggy in dark mode that’s ok, my question is: have you tested under light/day mode?
I am asking because sometimes if a CSS rule is broken it can cause other rules to be skipped.

**Comment by t1-tracey** [comment]
There were issues on github (https://githubstatus.com)
I merged this already but there was delay etc.

**Comment by skyventuree** [comment]
Since I use the CSS "prefers-color-scheme", it will mostly work on iOS devices.
I don't know about Android, I don't own any of them.
And I put all of the dark mode rules at the bottom so it should not be affecting other rules.

**Comment by jmmelko** [comment]
Why is this request still open, I thought Tracey approved it?

@Skyventuree could you please fix the text color? It should be white (against dark).

I think you need to add something in the following styles:

    body
    p, text.headers
    td


Thank you.

**Comment by skyventuree** [comment]
Sure, will fix it when I got a new keyboard. My PC keyboard is still broken as for now.

**Comment by jmmelko** [comment]
I am closing because this has been merged and I have just added the white text style for dark mode

**Comment by jmmelko** [comment]
I have added something at the song_meta: transcript_writer and stock_queries: transcript_writer entries.
@skyventuree: could you please translate these again?
No rush though.
Thank you.

**Pull request closed without merging**
