### PR TITLE
Encoding in open + cosmetic change

### PR DESCRIPTION
**Pull request by jmmelko**
* added encoding when opening a file, otherwise an error can be raised in some interpreters (eg Pythonista on a mobile). Just test that it still works on your computer (I have).
* small cosmetic adjustment for the ascii rendering of lyrics

### CODE REVIEW

**Comment by t1-tracey** [comment]
cool, I tested some file names and it worked :+1:

the roboto font seems not to support some characters but that's ok

**Comment by jmmelko** [comment]
I choose this font because it was plain and the first hit in google fonts.
But we can change. Which characters does it not support?

JMM.

**Comment by t1-tracey** [comment]
That’s ok :D I don’t know if other fonts can cover them either, so it’s alright.

The Unicode flat and sharps turned out as boxes ♭ ♯  (I just use them because I have on hand as a text replacement in iOS settings)

I tried some Vietnamese characters and they worked, like à ạ, Japanese turned out as boxes too, when I used こんにちは

**Comment by jmmelko** [comment]
mmmmhhhh...
We definitely have to handle japanese, and possibly Korean. But why Vietnamese?
I propose this font:

https://www.google.com/get/noto/help/cjk/

I don’t know if it supports flat and sharp. The only place where these symbols would appear is in the Recommended Key line. I have read that Arial can render these. So we can use Arial for this line. In the meantime they can replaced by 'b' and the sharp by '#'.

JMM.

**Comment by t1-tracey** [comment]
Yeah that sounds good! Sorry I just meant viet as one of the examples that I tested ^^ and yeah flat and sharp can be replaced with normal chars
>

**Pull request merged**
