### PR TITLE
Update Vietnamese Translation

### PR DESCRIPTION
**Pull request by jdewfiez**
Update vietnamese translation.
Not 100% accurate but I tried.

### CODE REVIEW

**Comment by jdewfiez** [comment]
the `Lang.py` need to add the vi_VN locale but I forgot to do so

**Comment by t1-tracey** [comment]
Wow this is awesome, no worries I can take care of `Lang.py`

**Comment by jdewfiez** [comment]
Gotta wait for the merge then, haha.

**Comment by t1-tracey** [comment]
sorry just had to get on my computer

**Comment by jmmelko** [comment]
I fell less on my own now.

Note that before these changes can be seen on the website and the bot, I have to learn how to fetch the locale on these platforms.

Besides, I have read that using os.getenv(‘LANG’) in the command line is not always secure, especially for people running an English Windows OS configured for another language (eg spanish). It is advised to interrogate a Windows DLL instead.
So we may have to create a “detect_locale” method with Try statements inside.
In case not locale is found, we may have to create a Query to ask the user to select a language.

What do you think?
Any hint appreciated.

**Comment by jdewfiez** [comment]
You can put the icon/link to select a language instead, most people do get annoyed by asking languages everytime they visit. 
_Except if you store the language reference in the user's cookie then it's cool._

**Comment by t1-tracey** [comment]
Oh I thought we were talking about the bot version here (link does not work for the bot, though it would for web)

Sent from my iPad

On 11 Apr 2020, at 7:44 pm, Roux Karlus <notifications@github.com> wrote:

﻿

You can put the icon/link to select a language instead, most people do get annoyed by asking languages everytime they visit.
Except if you store the language reference in the user's cookie then it's cool.

**Comment by jdewfiez** [comment]
Ah I see.

**Comment by t1-tracey** [comment]
the Vietnamese translation works^^ thank you so much jdewfiez!

image

btw I speak Viet as a second language XD but I am not confident in translating in professional settings in software (usually just use it at home, and for texting family)

**Comment by t1-tracey** [comment]
that was just the bot version where I set my locale manually (haven't gone to check the command line or web yet)

**Comment by t1-tracey** [comment]
if you want to see the bot ( https://discordapp.com/invite/ec4P25f )

**Comment by jmmelko** [comment]
Yes btw I haven’t found in the DiscordPy a way to get the user locale, I think this is considered private information.
So maybe we should react to a flag emoji to set the locale?

**Comment by jdewfiez** [comment]
That would be the best idea tbh

**Pull request merged**
